# Generated by Django 2.1.7 on 2019-03-18 02:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Optional label like "Part I" or "Meeting point"',
                        max_length=255,
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="EventGroupPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "is_regional_group",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "content",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "text",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    "h2",
                                                    "h3",
                                                    "h4",
                                                    "bold",
                                                    "italic",
                                                    "ul",
                                                    "ol",
                                                    "hr",
                                                    "link",
                                                    "document-link",
                                                ]
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alternative_title",
                                            wagtail.core.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "attribution",
                                            wagtail.core.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.core.blocks.URLBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "video",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ("video", wagtail.embeds.blocks.EmbedBlock()),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "message",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "message",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "text",
                                                        wagtail.core.blocks.RichTextBlock(
                                                            features=[
                                                                "h2",
                                                                "h3",
                                                                "h4",
                                                                "bold",
                                                                "italic",
                                                                "ul",
                                                                "ol",
                                                                "hr",
                                                                "link",
                                                                "document-link",
                                                            ]
                                                        ),
                                                    )
                                                ]
                                            ),
                                        ),
                                        (
                                            "font_size_factor",
                                            wagtail.core.blocks.FloatBlock(default=1),
                                        ),
                                        (
                                            "font_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.core.blocks.URLBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "carousel",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "items",
                                            wagtail.core.blocks.StreamBlock(
                                                [
                                                    (
                                                        "image",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(),
                                                                ),
                                                                (
                                                                    "alternative_title",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "attribution",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "link",
                                                                    wagtail.core.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "internal_link",
                                                                                wagtail.core.blocks.PageChooserBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "external_link",
                                                                                wagtail.core.blocks.URLBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "video",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "video",
                                                                    wagtail.embeds.blocks.EmbedBlock(),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "message",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "message",
                                                                    wagtail.core.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "text",
                                                                                wagtail.core.blocks.RichTextBlock(
                                                                                    features=[
                                                                                        "h2",
                                                                                        "h3",
                                                                                        "h4",
                                                                                        "bold",
                                                                                        "italic",
                                                                                        "ul",
                                                                                        "ol",
                                                                                        "hr",
                                                                                        "link",
                                                                                        "document-link",
                                                                                    ]
                                                                                ),
                                                                            )
                                                                        ]
                                                                    ),
                                                                ),
                                                                (
                                                                    "font_size_factor",
                                                                    wagtail.core.blocks.FloatBlock(
                                                                        default=1
                                                                    ),
                                                                ),
                                                                (
                                                                    "font_color",
                                                                    wagtail.core.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "xr-green",
                                                                                "XR green",
                                                                            ),
                                                                            (
                                                                                "xr-yellow",
                                                                                "XR yellow",
                                                                            ),
                                                                            (
                                                                                "xr-light-blue",
                                                                                "XR light blue",
                                                                            ),
                                                                            (
                                                                                "xr-dark-blue",
                                                                                "XR dark blue",
                                                                            ),
                                                                            (
                                                                                "xr-white",
                                                                                "XR white",
                                                                            ),
                                                                            (
                                                                                "xr-black",
                                                                                "XR black",
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                                (
                                                                    "background_color",
                                                                    wagtail.core.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "xr-green",
                                                                                "XR green",
                                                                            ),
                                                                            (
                                                                                "xr-yellow",
                                                                                "XR yellow",
                                                                            ),
                                                                            (
                                                                                "xr-light-blue",
                                                                                "XR light blue",
                                                                            ),
                                                                            (
                                                                                "xr-dark-blue",
                                                                                "XR dark blue",
                                                                            ),
                                                                            (
                                                                                "xr-white",
                                                                                "XR white",
                                                                            ),
                                                                            (
                                                                                "xr-black",
                                                                                "XR black",
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                                (
                                                                    "background_image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "link",
                                                                    wagtail.core.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "internal_link",
                                                                                wagtail.core.blocks.PageChooserBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "external_link",
                                                                                wagtail.core.blocks.URLBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "content",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "text",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    "h2",
                                                    "h3",
                                                    "h4",
                                                    "bold",
                                                    "italic",
                                                    "ul",
                                                    "ol",
                                                    "hr",
                                                    "link",
                                                    "document-link",
                                                ]
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alternative_title",
                                            wagtail.core.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "attribution",
                                            wagtail.core.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.core.blocks.URLBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "video",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ("video", wagtail.embeds.blocks.EmbedBlock()),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "message",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "message",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "text",
                                                        wagtail.core.blocks.RichTextBlock(
                                                            features=[
                                                                "h2",
                                                                "h3",
                                                                "h4",
                                                                "bold",
                                                                "italic",
                                                                "ul",
                                                                "ol",
                                                                "hr",
                                                                "link",
                                                                "document-link",
                                                            ]
                                                        ),
                                                    )
                                                ]
                                            ),
                                        ),
                                        (
                                            "font_size_factor",
                                            wagtail.core.blocks.FloatBlock(default=1),
                                        ),
                                        (
                                            "font_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.core.blocks.URLBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "carousel",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "items",
                                            wagtail.core.blocks.StreamBlock(
                                                [
                                                    (
                                                        "image",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(),
                                                                ),
                                                                (
                                                                    "alternative_title",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "attribution",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "link",
                                                                    wagtail.core.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "internal_link",
                                                                                wagtail.core.blocks.PageChooserBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "external_link",
                                                                                wagtail.core.blocks.URLBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "video",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "video",
                                                                    wagtail.embeds.blocks.EmbedBlock(),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "message",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "message",
                                                                    wagtail.core.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "text",
                                                                                wagtail.core.blocks.RichTextBlock(
                                                                                    features=[
                                                                                        "h2",
                                                                                        "h3",
                                                                                        "h4",
                                                                                        "bold",
                                                                                        "italic",
                                                                                        "ul",
                                                                                        "ol",
                                                                                        "hr",
                                                                                        "link",
                                                                                        "document-link",
                                                                                    ]
                                                                                ),
                                                                            )
                                                                        ]
                                                                    ),
                                                                ),
                                                                (
                                                                    "font_size_factor",
                                                                    wagtail.core.blocks.FloatBlock(
                                                                        default=1
                                                                    ),
                                                                ),
                                                                (
                                                                    "font_color",
                                                                    wagtail.core.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "xr-green",
                                                                                "XR green",
                                                                            ),
                                                                            (
                                                                                "xr-yellow",
                                                                                "XR yellow",
                                                                            ),
                                                                            (
                                                                                "xr-light-blue",
                                                                                "XR light blue",
                                                                            ),
                                                                            (
                                                                                "xr-dark-blue",
                                                                                "XR dark blue",
                                                                            ),
                                                                            (
                                                                                "xr-white",
                                                                                "XR white",
                                                                            ),
                                                                            (
                                                                                "xr-black",
                                                                                "XR black",
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                                (
                                                                    "background_color",
                                                                    wagtail.core.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "xr-green",
                                                                                "XR green",
                                                                            ),
                                                                            (
                                                                                "xr-yellow",
                                                                                "XR yellow",
                                                                            ),
                                                                            (
                                                                                "xr-light-blue",
                                                                                "XR light blue",
                                                                            ),
                                                                            (
                                                                                "xr-dark-blue",
                                                                                "XR dark blue",
                                                                            ),
                                                                            (
                                                                                "xr-white",
                                                                                "XR white",
                                                                            ),
                                                                            (
                                                                                "xr-black",
                                                                                "XR black",
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                                (
                                                                    "background_image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "link",
                                                                    wagtail.core.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "internal_link",
                                                                                wagtail.core.blocks.PageChooserBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "external_link",
                                                                                wagtail.core.blocks.URLBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="EventOrganiser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("url", models.URLField(blank=True)),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "description",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        help_text="The description is only visible on the detail page.",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="eventorganiser",
            name="event_page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="further_organisers",
                to="xr_events.EventPage",
            ),
        ),
        migrations.AddField(
            model_name="eventgrouppage",
            name="local_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_group_set",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AddField(
            model_name="eventdate",
            name="event_page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dates",
                to="xr_events.EventPage",
            ),
        ),
    ]
