# Generated by Django 2.1.7 on 2019-03-18 20:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [("xr_events", "0002_initial_event_pages_and_auth_groups")]

    operations = [
        migrations.AlterField(
            model_name="eventgrouppage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            "h2",
                                            "h3",
                                            "h4",
                                            "bold",
                                            "italic",
                                            "ul",
                                            "ol",
                                            "hr",
                                            "link",
                                            "document-link",
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "alternative_title",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "attribution",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.core.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("video", wagtail.embeds.blocks.EmbedBlock()),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "message",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "message",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.RichTextBlock(
                                                    features=[
                                                        "h2",
                                                        "h3",
                                                        "h4",
                                                        "bold",
                                                        "italic",
                                                        "ul",
                                                        "ol",
                                                        "hr",
                                                        "link",
                                                        "document-link",
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    "font_size_factor",
                                    wagtail.core.blocks.FloatBlock(default=1),
                                ),
                                (
                                    "font_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.core.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "carousel",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                        ),
                                                        (
                                                            "alternative_title",
                                                            wagtail.core.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "caption",
                                                            wagtail.core.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "attribution",
                                                            wagtail.core.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "internal_link",
                                                                        wagtail.core.blocks.PageChooserBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "external_link",
                                                                        wagtail.core.blocks.URLBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "video",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "video",
                                                            wagtail.embeds.blocks.EmbedBlock(),
                                                        ),
                                                        (
                                                            "caption",
                                                            wagtail.core.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "message",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "message",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "text",
                                                                        wagtail.core.blocks.RichTextBlock(
                                                                            features=[
                                                                                "h2",
                                                                                "h3",
                                                                                "h4",
                                                                                "bold",
                                                                                "italic",
                                                                                "ul",
                                                                                "ol",
                                                                                "hr",
                                                                                "link",
                                                                                "document-link",
                                                                            ]
                                                                        ),
                                                                    )
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "font_size_factor",
                                                            wagtail.core.blocks.FloatBlock(
                                                                default=1
                                                            ),
                                                        ),
                                                        (
                                                            "font_color",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "xr-green",
                                                                        "XR green",
                                                                    ),
                                                                    (
                                                                        "xr-yellow",
                                                                        "XR yellow",
                                                                    ),
                                                                    (
                                                                        "xr-light-blue",
                                                                        "XR light blue",
                                                                    ),
                                                                    (
                                                                        "xr-dark-blue",
                                                                        "XR dark blue",
                                                                    ),
                                                                    (
                                                                        "xr-white",
                                                                        "XR white",
                                                                    ),
                                                                    (
                                                                        "xr-black",
                                                                        "XR black",
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "background_color",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "xr-green",
                                                                        "XR green",
                                                                    ),
                                                                    (
                                                                        "xr-yellow",
                                                                        "XR yellow",
                                                                    ),
                                                                    (
                                                                        "xr-light-blue",
                                                                        "XR light blue",
                                                                    ),
                                                                    (
                                                                        "xr-dark-blue",
                                                                        "XR dark blue",
                                                                    ),
                                                                    (
                                                                        "xr-white",
                                                                        "XR white",
                                                                    ),
                                                                    (
                                                                        "xr-black",
                                                                        "XR black",
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "background_image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "internal_link",
                                                                        wagtail.core.blocks.PageChooserBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "external_link",
                                                                        wagtail.core.blocks.URLBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventgrouppage",
            name="local_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_group_set",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AlterField(
            model_name="eventlistpage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            "h2",
                                            "h3",
                                            "h4",
                                            "bold",
                                            "italic",
                                            "ul",
                                            "ol",
                                            "hr",
                                            "link",
                                            "document-link",
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "alternative_title",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "attribution",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.core.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("video", wagtail.embeds.blocks.EmbedBlock()),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(required=False),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "message",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "message",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.RichTextBlock(
                                                    features=[
                                                        "h2",
                                                        "h3",
                                                        "h4",
                                                        "bold",
                                                        "italic",
                                                        "ul",
                                                        "ol",
                                                        "hr",
                                                        "link",
                                                        "document-link",
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    "font_size_factor",
                                    wagtail.core.blocks.FloatBlock(default=1),
                                ),
                                (
                                    "font_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.core.blocks.URLBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "carousel",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                        ),
                                                        (
                                                            "alternative_title",
                                                            wagtail.core.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "caption",
                                                            wagtail.core.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "attribution",
                                                            wagtail.core.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "internal_link",
                                                                        wagtail.core.blocks.PageChooserBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "external_link",
                                                                        wagtail.core.blocks.URLBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "video",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "video",
                                                            wagtail.embeds.blocks.EmbedBlock(),
                                                        ),
                                                        (
                                                            "caption",
                                                            wagtail.core.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "message",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "message",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "text",
                                                                        wagtail.core.blocks.RichTextBlock(
                                                                            features=[
                                                                                "h2",
                                                                                "h3",
                                                                                "h4",
                                                                                "bold",
                                                                                "italic",
                                                                                "ul",
                                                                                "ol",
                                                                                "hr",
                                                                                "link",
                                                                                "document-link",
                                                                            ]
                                                                        ),
                                                                    )
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "font_size_factor",
                                                            wagtail.core.blocks.FloatBlock(
                                                                default=1
                                                            ),
                                                        ),
                                                        (
                                                            "font_color",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "xr-green",
                                                                        "XR green",
                                                                    ),
                                                                    (
                                                                        "xr-yellow",
                                                                        "XR yellow",
                                                                    ),
                                                                    (
                                                                        "xr-light-blue",
                                                                        "XR light blue",
                                                                    ),
                                                                    (
                                                                        "xr-dark-blue",
                                                                        "XR dark blue",
                                                                    ),
                                                                    (
                                                                        "xr-white",
                                                                        "XR white",
                                                                    ),
                                                                    (
                                                                        "xr-black",
                                                                        "XR black",
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "background_color",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "xr-green",
                                                                        "XR green",
                                                                    ),
                                                                    (
                                                                        "xr-yellow",
                                                                        "XR yellow",
                                                                    ),
                                                                    (
                                                                        "xr-light-blue",
                                                                        "XR light blue",
                                                                    ),
                                                                    (
                                                                        "xr-dark-blue",
                                                                        "XR dark blue",
                                                                    ),
                                                                    (
                                                                        "xr-white",
                                                                        "XR white",
                                                                    ),
                                                                    (
                                                                        "xr-black",
                                                                        "XR black",
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "background_image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "internal_link",
                                                                        wagtail.core.blocks.PageChooserBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "external_link",
                                                                        wagtail.core.blocks.URLBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
