# Generated by Django 2.1.7 on 2019-03-24 18:26

from django.db import migrations


def set_localgroup_references(apps, schema_editor):
    LocalGroup = apps.get_model("xr_pages", "LocalGroup")
    LocalGroupPage = apps.get_model("xr_pages", "LocalGroupPage")
    EventGroupPage = apps.get_model("xr_events", "EventGroupPage")
    EventPage = apps.get_model("xr_events", "EventPage")

    for event_group_page in EventGroupPage.objects.all():
        if event_group_page.is_regional_group:
            group_name = "Deutschland"
        elif event_group_page.local_group:
            local_group = event_group_page.local_group
            local_group_page = LocalGroupPage.objects.get(pk=local_group.pk)
            group_name = local_group_page.name
        else:
            raise ValueError(
                "EventGroupPage '%s' has no local_group_page assigned. Please "
                "assign "
                "a local_group_page in order to run the migration."
            )

        local_group, created = LocalGroup.objects.get_or_create(name=group_name)
        if event_group_page.is_regional_group:
            LocalGroup.objects.filter(pk=local_group.pk).update(is_regional_group=True)

        EventGroupPage.objects.filter(pk=event_group_page.pk).update(group=local_group)

        # update event_group_page children
        EventPage.objects.filter(path__startswith=event_group_page.path).update(
            group=local_group
        )


class Migration(migrations.Migration):

    dependencies = [
        ("xr_events", "0004_add_localgroup_references_and_adjust_event_fields"),
        ("xr_pages", "0025_data_set_localgroup_references"),
    ]

    operations = [
        migrations.RunPython(set_localgroup_references, migrations.RunPython.noop)
    ]
