# Generated by Django 2.1.7 on 2019-03-26 00:39

from django.db import migrations
from django.db.models import F


def populate_evetpage_startdate_and_enddate(apps, schema_editor):
    EventPage = apps.get_model("xr_events", "EventPage")

    for event in EventPage.objects.all():
        if event.dates.exists():
            start_date = (
                event.dates.all()
                .order_by(F("start").asc(nulls_last=True))
                .first()
                .start
            )
            end_date = (
                event.dates.all().order_by(F("end").desc(nulls_last=True)).first().end
            )
            EventPage.objects.filter(pk=event.pk).update(
                start_date=start_date, end_date=end_date
            )


class Migration(migrations.Migration):

    dependencies = [("xr_events", "0006_eventpage_model_add_startdate_and_enddate")]

    operations = [
        migrations.RunPython(
            populate_evetpage_startdate_and_enddate, migrations.RunPython.noop
        )
    ]
