# Generated by Django 2.1.7 on 2019-04-06 09:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [("xr_events", "0008_remove_old_group_fields")]

    operations = [
        migrations.AlterField(
            model_name="eventgrouppage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            "h3",
                                            "h4",
                                            "bold",
                                            "italic",
                                            "ul",
                                            "ol",
                                            "hr",
                                            "link",
                                            "document-link",
                                        ],
                                        help_text="Simple richtext with basic formatting. Use links in order to connect related pages frequently. Ordered lists are rendered with big numbers.For images and videos use the image and video blocks.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "alternative_title",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional alternative title, which is displayed on hover. If not given, the image's title attribute will be used instead.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional copyright or attribution text, which is displayed at the bottom right of the image.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    help_text='Link to an internal page. Is overwritten by "external link".',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.core.blocks.URLBlock(
                                                    help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("center", "Center"),
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ],
                                        help_text="Choose the alignment of the block.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                ("video", wagtail.embeds.blocks.EmbedBlock()),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("center", "Center"),
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ],
                                        help_text="Choose the alignment of the block.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "message",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "message",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="The message to display. Text will be centered and linebreaks will be preserved.",
                                        required=False,
                                        rows=1,
                                    ),
                                ),
                                (
                                    "font_size",
                                    wagtail.core.blocks.IntegerBlock(
                                        default=40,
                                        help_text="Adjust the font size to fit your needs. Use the preview feature to see how big the font will be rendered.",
                                    ),
                                ),
                                (
                                    "font_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    help_text='Link to an internal page. Is overwritten by "external link".',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.core.blocks.URLBlock(
                                                    help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("center", "Center"),
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ],
                                        help_text="Choose the alignment of the block.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "form",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "form_page",
                                    wagtail.core.blocks.PageChooserBlock(
                                        [
                                            "xr_newsletter.EmailFormPage",
                                            "xr_newsletter.NewsletterFormPage",
                                        ]
                                    ),
                                ),
                                (
                                    "font_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventlistpage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            "h3",
                                            "h4",
                                            "bold",
                                            "italic",
                                            "ul",
                                            "ol",
                                            "hr",
                                            "link",
                                            "document-link",
                                        ],
                                        help_text="Simple richtext with basic formatting. Use links in order to connect related pages frequently. Ordered lists are rendered with big numbers.For images and videos use the image and video blocks.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "alternative_title",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional alternative title, which is displayed on hover. If not given, the image's title attribute will be used instead.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional copyright or attribution text, which is displayed at the bottom right of the image.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    help_text='Link to an internal page. Is overwritten by "external link".',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.core.blocks.URLBlock(
                                                    help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("center", "Center"),
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ],
                                        help_text="Choose the alignment of the block.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                ("video", wagtail.embeds.blocks.EmbedBlock()),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("center", "Center"),
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ],
                                        help_text="Choose the alignment of the block.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "message",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "message",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="The message to display. Text will be centered and linebreaks will be preserved.",
                                        required=False,
                                        rows=1,
                                    ),
                                ),
                                (
                                    "font_size",
                                    wagtail.core.blocks.IntegerBlock(
                                        default=40,
                                        help_text="Adjust the font size to fit your needs. Use the preview feature to see how big the font will be rendered.",
                                    ),
                                ),
                                (
                                    "font_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    help_text='Link to an internal page. Is overwritten by "external link".',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.core.blocks.URLBlock(
                                                    help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("center", "Center"),
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ],
                                        help_text="Choose the alignment of the block.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "form",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "form_page",
                                    wagtail.core.blocks.PageChooserBlock(
                                        [
                                            "xr_newsletter.EmailFormPage",
                                            "xr_newsletter.NewsletterFormPage",
                                        ]
                                    ),
                                ),
                                (
                                    "font_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=[
                                            "h3",
                                            "h4",
                                            "bold",
                                            "italic",
                                            "ul",
                                            "ol",
                                            "hr",
                                            "link",
                                            "document-link",
                                        ],
                                        help_text="Simple richtext with basic formatting. Use links in order to connect related pages frequently. Ordered lists are rendered with big numbers.For images and videos use the image and video blocks.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "alternative_title",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional alternative title, which is displayed on hover. If not given, the image's title attribute will be used instead.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional copyright or attribution text, which is displayed at the bottom right of the image.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    help_text='Link to an internal page. Is overwritten by "external link".',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.core.blocks.URLBlock(
                                                    help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("center", "Center"),
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ],
                                        help_text="Choose the alignment of the block.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                ("video", wagtail.embeds.blocks.EmbedBlock()),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("center", "Center"),
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ],
                                        help_text="Choose the alignment of the block.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "message",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "message",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="The message to display. Text will be centered and linebreaks will be preserved.",
                                        required=False,
                                        rows=1,
                                    ),
                                ),
                                (
                                    "font_size",
                                    wagtail.core.blocks.IntegerBlock(
                                        default=40,
                                        help_text="Adjust the font size to fit your needs. Use the preview feature to see how big the font will be rendered.",
                                    ),
                                ),
                                (
                                    "font_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "internal_link",
                                                wagtail.core.blocks.PageChooserBlock(
                                                    help_text='Link to an internal page. Is overwritten by "external link".',
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "external_link",
                                                wagtail.core.blocks.URLBlock(
                                                    help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("center", "Center"),
                                            ("full_content", "Full content"),
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("full_page", "Full page"),
                                        ],
                                        help_text="Choose the alignment of the block.",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "form",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional heading, which is displayed above the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "form_page",
                                    wagtail.core.blocks.PageChooserBlock(
                                        [
                                            "xr_newsletter.EmailFormPage",
                                            "xr_newsletter.NewsletterFormPage",
                                        ]
                                    ),
                                ),
                                (
                                    "font_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("xr-green", "XR green"),
                                            ("xr-yellow", "XR yellow"),
                                            ("xr-light-blue", "XR light blue"),
                                            ("xr-dark-blue", "XR dark blue"),
                                            ("xr-white", "XR white"),
                                            ("xr-black", "XR black"),
                                        ]
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="An optional caption, which is displayed below the block's content.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="An optional description, which is displayed below the block's caption",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                help_text="The content is only visible on the detail page.",
            ),
        ),
    ]
