# Generated by Django 2.1.7 on 2019-05-05 13:47

from django.db import migrations


def populate_eventlistpage_group(apps, schema_editor):
    LocalGroup = apps.get_model("xr_pages", "LocalGroup")
    EventListPage = apps.get_model("xr_events", "EventListPage")

    regional_group = LocalGroup.objects.get(is_regional_group=True)

    event_list_page = EventListPage.objects.get()
    event_list_page.group = regional_group
    event_list_page.save()


class Migration(migrations.Migration):

    dependencies = [("xr_events", "0012_add_eventlistpage_group")]

    operations = [
        migrations.RunPython(populate_eventlistpage_group, migrations.RunPython.noop)
    ]
