# Generated by Django 2.1.7 on 2019-05-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("xr_events", "0014_eventlistpage_group_null_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventgrouppage",
            name="default_event_image",
            field=models.ForeignKey(
                blank=True,
                help_text="A default image as Fallback for events, that have no image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="eventlistpage",
            name="default_event_image",
            field=models.ForeignKey(
                blank=True,
                help_text="A default image as Fallback for events, that have no image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
