# Generated by Django 2.1.7 on 2019-02-25 18:50

from django.db import migrations


def replace_wagtail_homepage_with_xr_homepage(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")
    Page = apps.get_model("wagtailcore.Page")
    Site = apps.get_model("wagtailcore.Site")
    StandardPage = apps.get_model("xr_pages.StandardPage")

    # Create xr page content type
    xr_page_content_type, created = ContentType.objects.get_or_create(
        model="standardpage", app_label="xr_pages"
    )

    # get wagtail homepage
    wagtail_homepage = Page.objects.get(path="00010001")

    # Create xr homepage
    xr_homepage = StandardPage.objects.create(
        title="extionction rebellion DE",
        slug="home",
        content_type=xr_page_content_type,
        path="00010002",
        depth=2,
        numchild=wagtail_homepage.numchild,
        url_path="/home/",
    )

    # assign new homepage to localhost site
    site = Site.objects.get(root_page_id=wagtail_homepage.id)
    site.root_page_id = xr_homepage.id
    site.save()

    # remove wagtail homepage
    wagtail_homepage.delete()

    # move xr homepage
    xr_homepage.path = "00010001"
    xr_homepage.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0002_alter_content_streamfield")]

    operations = [
        migrations.RunPython(replace_wagtail_homepage_with_xr_homepage, reverse)
    ]
