# Generated by Django 2.1.7 on 2019-03-08 20:13

from django.db import migrations


def add_common_collection_data(apps, schema_editor):
    Collection = apps.get_model("wagtailcore.Collection")

    # Get Root Collection
    root_collection = Collection.objects.get(path="0001")
    root_collection.numchild = 1
    root_collection.save()

    # Create common collection
    Collection.objects.create(name="Common", path="00010001", depth=2, numchild=0)


class Migration(migrations.Migration):

    dependencies = [
        ("xr_pages", "0005_replace_homepage_and_add_local_group_index_page")
    ]

    operations = [
        migrations.RunPython(add_common_collection_data, migrations.RunPython.noop)
    ]
