# Generated by Django 2.1.7 on 2019-03-10 15:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailmenus", "0022_auto_20170913_2125"),
        ("wagtailforms", "0003_capitalizeverbose"),
        ("xr_pages", "0007_localgroupsubpage"),
    ]

    operations = [
        migrations.RenameModel(old_name="StandardPage", new_name="HomeSubPage")
    ]
