# Generated by Django 2.1.7 on 2019-03-14 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailmenus", "0022_auto_20170913_2125"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailforms", "0003_capitalizeverbose"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("xr_pages", "0009_alter_and_add_basic_auth_groups"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LocalGroupIndexPage", new_name="LocalGroupListPage"
        )
    ]
