# Generated by Django 2.1.7 on 2019-03-14 18:27

from django.db import migrations


def adjust_localgrouplistpage_pagerevisions(apps, schema_editor):
    PageRevision = apps.get_model("wagtailcore.PageRevision")
    LocalGroupListPage = apps.get_model("xr_pages.LocalGroupListPage")

    local_group_list_page = LocalGroupListPage.objects.first()

    # remove page revisions
    PageRevision.objects.filter(page=local_group_list_page).delete()

    local_group_list_page.live_revision = None
    local_group_list_page.latest_revision_created_at = None
    local_group_list_page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("xr_pages", "0010_renamed_model_localgroupindexpage_to_localgrouplistpage")
    ]

    operations = [
        migrations.RunPython(
            adjust_localgrouplistpage_pagerevisions, migrations.RunPython.noop
        )
    ]
