# Generated by Django 2.1.7 on 2019-03-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0012_rename_page_auth_groups")]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="group_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="group_name",
            field=models.CharField(default="Deutschland", max_length=50),
        ),
        migrations.AddField(
            model_name="localgrouppage",
            name="name",
            field=models.CharField(
                default="",
                help_text='The unique name for the local group. Used as label for links referring to this page. Enter a name without leading "XR ".',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="localgrouppage",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BW", "Baden-Württemberg"),
                    ("BY", "Bayern"),
                    ("BE", "Berlin"),
                    ("BB", "Brandenburg"),
                    ("HB", "Bremen"),
                    ("HH", "Hamburg"),
                    ("HE", "Hessen"),
                    ("MV", "Mecklenburg-Vorpommern"),
                    ("NI", "Niedersachsen"),
                    ("NW", "Nordrhein-Westfalen"),
                    ("RP", "Rheinland-Pfalz"),
                    ("SL", "Saarland"),
                    ("SN", "Sachsen"),
                    ("ST", "Sachsen-Anhalt"),
                    ("SH", "Schleswig-Holstein"),
                    ("TH", "Thüringen"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
