# Generated by Django 2.1.7 on 2019-03-18 00:19

from django.db import migrations


def populate_local_group_names(apps, schema_editor):
    LocalGroupPage = apps.get_model("xr_pages.LocalGroupPage")

    for local_group_page in LocalGroupPage.objects.all():
        local_group_page.name = local_group_page.title
        local_group_page.save()


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0013_add_group_fields_name_email_state")]

    operations = [
        migrations.RunPython(populate_local_group_names, migrations.RunPython.noop)
    ]
