# Generated by Django 2.1.7 on 2019-03-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0014_populate_localgrouppage_names")]

    operations = [
        migrations.AlterField(
            model_name="localgrouppage",
            name="name",
            field=models.CharField(
                default="",
                help_text='The unique name for the local group. Used as label for links referring to this page. Enter a name without leading "XR ".',
                max_length=50,
                unique=True,
            ),
        )
    ]
