# Generated by Django 2.1.7 on 2019-03-18 01:45

from django.db import migrations


def rename_xr_de_page_groups(apps, schema_editor):
    Group = apps.get_model("auth.Group")

    # rename existing page auth groups
    for group_type in ["Editors", "Moderators"]:
        group = Group.objects.get(name="XR de Page %s" % group_type)
        group.name = "Deutschland Page %s" % group_type
        group.save()


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0015_set_localgrouppage_name_unique_true")]

    operations = [
        migrations.RunPython(rename_xr_de_page_groups, migrations.RunPython.noop)
    ]
