# Generated by Django 2.1.7 on 2019-03-19 00:02

from django.db import migrations


def change_homepage_title(apps, schema_editor):
    HomePage = apps.get_model("xr_pages", "HomePage")
    homepage = HomePage.objects.get()
    if homepage.title == "extionction rebellion DE":
        homepage.title = "XR Deutschland"
        homepage.save()


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0018_page_content_fields_allow_blank")]

    operations = [
        migrations.RunPython(change_homepage_title, migrations.RunPython.noop)
    ]
