# Generated by Django 2.1.7 on 2019-03-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0020_sanitize_group_premissions")]

    operations = [
        migrations.AddField(
            model_name="localgrouppage",
            name="is_regional_group",
            field=models.BooleanField(default=False, editable=False),
        )
    ]
