# Generated by Django 2.1.7 on 2019-03-23 10:13

from django.db import migrations


def add_special_regional_group_page(apps, schema_editor):
    LocalGroupPage = apps.get_model("xr_pages.LocalGroupPage")

    local_group_page = LocalGroupPage.objects.get(is_regional_group=True)
    local_group_page.live = False
    local_group_page.save()


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0022_data_add_special_regional_group_page")]

    operations = [
        migrations.RunPython(add_special_regional_group_page, migrations.RunPython.noop)
    ]
