# Generated by Django 2.1.7 on 2019-03-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("xr_pages", "0023_data_depublish_regional_group_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_regional_group",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text='The unique name for the local group. Used as label for links referring to this page. Enter a name without leading "XR ".',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "old_name",
                    models.CharField(default="", editable=False, max_length=50),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="A description not only for the detail view, but also for lists, teasers or social media.",
                        max_length=254,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BW", "Baden-Württemberg"),
                            ("BY", "Bayern"),
                            ("BE", "Berlin"),
                            ("BB", "Brandenburg"),
                            ("HB", "Bremen"),
                            ("HH", "Hamburg"),
                            ("HE", "Hessen"),
                            ("MV", "Mecklenburg-Vorpommern"),
                            ("NI", "Niedersachsen"),
                            ("NW", "Nordrhein-Westfalen"),
                            ("RP", "Rheinland-Pfalz"),
                            ("SL", "Saarland"),
                            ("SN", "Sachsen"),
                            ("ST", "Sachsen-Anhalt"),
                            ("SH", "Schleswig-Holstein"),
                            ("TH", "Thüringen"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text='Some city or address, like you would enter in GMaps or OpenStreetMap, e.g. "Berlin", "Somestreet 84, 12345 Samplecity".',
                        max_length=255,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="An image that can be used not only for the detail view, but also for lists, teasers or social media.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="localgrouppage",
            name="group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="xr_pages.LocalGroup",
            ),
        ),
        migrations.AddField(
            model_name="localgroupsubpage",
            name="group",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="xr_pages.LocalGroup",
            ),
        ),
    ]
