# Generated by Django 2.1.7 on 2019-03-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0025_data_set_localgroup_references")]

    operations = [
        migrations.AlterModelOptions(
            name="localgroup",
            options={"verbose_name": "Group", "verbose_name_plural": "Gruppen"},
        ),
        migrations.RemoveField(model_name="homepage", name="group_email"),
        migrations.RemoveField(model_name="homepage", name="group_name"),
        migrations.RemoveField(model_name="localgrouppage", name="email"),
        migrations.RemoveField(model_name="localgrouppage", name="is_regional_group"),
        migrations.RemoveField(model_name="localgrouppage", name="name"),
        migrations.RemoveField(model_name="localgrouppage", name="state"),
        migrations.AlterField(
            model_name="localgrouppage",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="xr_pages.LocalGroup"
            ),
        ),
        migrations.AlterField(
            model_name="localgroupsubpage",
            name="group",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="xr_pages.LocalGroup",
            ),
        ),
    ]
