# Generated by Django 2.1.7 on 2019-04-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0026_remove_old_group_fields")]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="group",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="xr_pages.LocalGroup",
            ),
        ),
        migrations.AddField(
            model_name="homesubpage",
            name="group",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="xr_pages.LocalGroup",
            ),
        ),
    ]
