# Generated by Django 2.1.7 on 2019-04-19 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0033_update_local_group_fields")]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="founding_date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                verbose_name="Founding date",
            ),
        ),
        migrations.AddField(
            model_name="localgroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Aktiv"),
                    ("looking_for_people", "looking for people"),
                    ("idle", "idle"),
                ],
                default="active",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
