# Generated by Django 2.1.7 on 2019-04-19 03:54

from django.db import migrations, models
import django.db.models.deletion


def populate_localgroup_site(apps, schema_editor):
    Site = apps.get_model("wagtailcore.Site")
    LocalGroup = apps.get_model("xr_pages.LocalGroup")

    site = Site.objects.get(is_default_site=True)

    for local_group in LocalGroup.objects.all():
        local_group.site = site
        local_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("xr_pages", "0034_add_status_and_founded_to_local_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="site",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.Site",
                verbose_name="Webseite",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_localgroup_site, migrations.RunPython.noop),
    ]
