# Generated by Django 2.1.7 on 2019-05-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("xr_pages", "0036_data_remove_regional_group_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ein Beschreibung, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Ein Bild, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="homesubpage",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ein Beschreibung, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="homesubpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Ein Bild, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="localgrouplistpage",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ein Beschreibung, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="localgrouplistpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Ein Bild, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="localgrouppage",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ein Beschreibung, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="localgrouppage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Ein Bild, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="localgroupsubpage",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ein Beschreibung, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="localgroupsubpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Ein Bild, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
