# Generated by Django 2.1.7 on 2019-05-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0038_add_local_group_social_media_fields")]

    operations = [
        migrations.AddField(
            model_name="localgrouplistpage",
            name="group",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="xr_pages.LocalGroup",
            ),
        )
    ]
