# Generated by Django 2.1.7 on 2019-05-05 13:39

from django.db import migrations


def populate_localgroulistpage_group(apps, schema_editor):
    LocalGroup = apps.get_model("xr_pages", "LocalGroup")
    LocalGroupListPage = apps.get_model("xr_pages", "LocalGroupListPage")

    regional_group = LocalGroup.objects.get(is_regional_group=True)

    local_group_list_page = LocalGroupListPage.objects.get()
    local_group_list_page.group = regional_group
    local_group_list_page.save()


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0039_localgrouplistpage_group")]

    operations = [
        migrations.RunPython(
            populate_localgroulistpage_group, migrations.RunPython.noop
        )
    ]
