# Generated by Django 2.1.7 on 2019-05-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0040_data_set_localgrouplistpage_group")]

    operations = [
        migrations.AlterField(
            model_name="localgrouplistpage",
            name="group",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="xr_pages.LocalGroup",
            ),
        )
    ]
