# Generated by Django 2.1.7 on 2019-05-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0042_show_page_title")]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="area_description",
            field=models.TextField(
                blank=True,
                help_text="More information about the area the group is active in.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="localgroup",
            name="gpg_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="localgroup",
            name="founding_date",
            field=models.DateField(blank=True, null=True, verbose_name="Founding date"),
        ),
        migrations.AlterField(
            model_name="localgroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Aktiv"),
                    ("in_foundation", "in foundation"),
                    ("looking_for_people", "looking for people"),
                    ("idle", "idle"),
                ],
                default="active",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
