# Generated by Django 2.1.7 on 2019-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0043_update_localgroup_fields")]

    operations = [
        migrations.RemoveField(model_name="localgroup", name="gpg_key"),
        migrations.AddField(
            model_name="localgroup",
            name="pgp_key_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
