# Generated by Django 2.2.2 on 2019-06-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0047_alter_streamfields")]

    operations = [
        migrations.CreateModel(
            name="VideoThumbnail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="video_thumbnails/")),
                ("uuid", models.CharField(max_length=32)),
                ("source_url", models.URLField()),
            ],
        )
    ]
