# Generated by Django 2.2.2 on 2019-09-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0049_add_mastodon")]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="latlng",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto discovered latitude and longitude. Comma separated.",
                max_length=255,
            ),
        )
    ]
