# Generated by Django 2.2.2 on 2019-09-24 15:21

from django.db import migrations
import geocoder


def add_lnglat(apps, schema_editor):
    LocalGroup = apps.get_model("xr_pages.LocalGroup")

    for group in LocalGroup.objects.all():
        if group.location:
            result = geocoder.osm(group.location)
            if result and result.json and "lat" in result.json and "lng" in result.json:
                lnglat = "{lng},{lat}".format(
                    lng=result.json["lng"], lat=result.json["lat"]
                )
                group.lnglat = lnglat
        else:
            group.lnglat = ""

        group.save()


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0050_add_lnglat")]

    operations = [migrations.RunPython(add_lnglat, migrations.RunPython.noop)]
