# Generated by Django 2.2.2 on 2019-09-24 15:21

from django.db import migrations


def add_latlng(apps, schema_editor):
    LocalGroup = apps.get_model("xr_pages.LocalGroup")

    for group in LocalGroup.objects.all():
        group.save()


class Migration(migrations.Migration):

    dependencies = [("xr_pages", "0050_add_latlng")]

    operations = [migrations.RunPython(add_latlng, migrations.RunPython.noop)]
