# Generated by Django 2.2.2 on 2019-10-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CachedImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cached_images")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("original_url", models.URLField(unique=True)),
            ],
        )
    ]
