# Generated by Django 2.2.2 on 2019-07-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("xr_newsletter", "0008_alter_streamfields")]

    operations = [
        migrations.AddField(
            model_name="emailformfield",
            name="placeholder",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The placeholder is displayed in grey, and disappears on focus.",
                max_length=255,
                verbose_name="placeholder",
            ),
        ),
        migrations.AddField(
            model_name="newsletterformfield",
            name="placeholder",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The placeholder is displayed in grey, and disappears on focus.",
                max_length=255,
                verbose_name="placeholder",
            ),
        ),
        migrations.AddField(
            model_name="newsletterformpage",
            name="mautic_form_id",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newsletterformfield",
            name="name",
            field=models.CharField(
                help_text="Ein eindeutiger name für das Formularfeld",
                max_length=255,
                verbose_name="Name",
            ),
        ),
    ]
