# Generated by Django 2.2.2 on 2019-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("xr_newsletter", "0010_alter_field_group_to_foreignkey")]

    operations = [
        migrations.AddField(
            model_name="emailformpage",
            name="save_submission",
            field=models.BooleanField(blank=True, default=False),
        )
    ]
