# Generated by Django 2.2.2 on 2019-07-19 16:49

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtailimages", "0001_squashed_0021"),
        ("xr_pages", "0047_alter_streamfields"),
        ("xr_newsletter", "0011_emailformpage_save_submission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThankYouPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ein Beschreibung, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                        max_length=254,
                    ),
                ),
                ("show_page_title", models.BooleanField(default=True)),
                (
                    "content",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "title",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ("title", wagtail.core.blocks.CharBlock()),
                                        (
                                            "font_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "Green"),
                                                    ("xr-black", "Black"),
                                                    ("xr-lemon", "Lemon"),
                                                    ("xr-light-blue", "Light blue"),
                                                    ("xr-pink", "Pink"),
                                                    ("xr-purple", "Purple"),
                                                    ("xr-light-green", "Light green"),
                                                    ("xr-warm-yellow", "Warm yellow"),
                                                    ("xr-bright-pink", "Bright pink"),
                                                    ("xr-red", "Red"),
                                                    ("xr-dark-blue", "Dark blue"),
                                                    ("xr-angry", "Angry"),
                                                    ("xr-white", "White"),
                                                    ("xr-light-grey", "Light grey"),
                                                    ("xr-grey", "Grey"),
                                                    ("xr-dark-grey", "Dark grey"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("left", "Left"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "text",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    "h2",
                                                    "h3",
                                                    "h4",
                                                    "bold",
                                                    "italic",
                                                    "ul",
                                                    "ol",
                                                    "hr",
                                                    "link",
                                                    "document-link",
                                                ],
                                                help_text="Simple richtext with basic formatting. Use links in order to connect related pages frequently. Ordered lists are rendered with big numbers.For images and videos use the image and video blocks.",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alternative_title",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional alternative title, which is displayed on hover. If not given, the image's title attribute will be used instead.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    (
                                                        "xr-transparent",
                                                        "None / Transparent",
                                                    ),
                                                    ("xr-green", "Green"),
                                                    ("xr-black", "Black"),
                                                    ("xr-lemon", "Lemon"),
                                                    ("xr-light-blue", "Light blue"),
                                                    ("xr-pink", "Pink"),
                                                    ("xr-purple", "Purple"),
                                                    ("xr-light-green", "Light green"),
                                                    ("xr-warm-yellow", "Warm yellow"),
                                                    ("xr-bright-pink", "Bright pink"),
                                                    ("xr-red", "Red"),
                                                    ("xr-dark-blue", "Dark blue"),
                                                    ("xr-angry", "Angry"),
                                                    ("xr-white", "White"),
                                                    ("xr-light-grey", "Light grey"),
                                                    ("xr-grey", "Grey"),
                                                    ("xr-dark-grey", "Dark grey"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "attribution",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional copyright or attribution text, which is displayed at the bottom right of the image.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            help_text='Link to an internal page. Is overwritten by "external link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.core.blocks.URLBlock(
                                                            help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "teaser",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "page",
                                            wagtail.core.blocks.PageChooserBlock(),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content. Overwrites the page title of the linked page.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption. Overwrites the page description of the linked page.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "video",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        ("video", wagtail.embeds.blocks.EmbedBlock()),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "slogan",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="The text is displayed centered and linebreaks will be preserved.",
                                                required=False,
                                                rows=1,
                                            ),
                                        ),
                                        (
                                            "font_size",
                                            wagtail.core.blocks.IntegerBlock(
                                                default=40,
                                                help_text="Adjust the font size to fit your needs. Use the preview feature to see how big the font will be rendered.",
                                            ),
                                        ),
                                        (
                                            "font_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "Green"),
                                                    ("xr-black", "Black"),
                                                    ("xr-lemon", "Lemon"),
                                                    ("xr-light-blue", "Light blue"),
                                                    ("xr-pink", "Pink"),
                                                    ("xr-purple", "Purple"),
                                                    ("xr-light-green", "Light green"),
                                                    ("xr-warm-yellow", "Warm yellow"),
                                                    ("xr-bright-pink", "Bright pink"),
                                                    ("xr-red", "Red"),
                                                    ("xr-dark-blue", "Dark blue"),
                                                    ("xr-angry", "Angry"),
                                                    ("xr-white", "White"),
                                                    ("xr-light-grey", "Light grey"),
                                                    ("xr-grey", "Grey"),
                                                    ("xr-dark-grey", "Dark grey"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    (
                                                        "xr-transparent",
                                                        "None / Transparent",
                                                    ),
                                                    ("xr-green", "Green"),
                                                    ("xr-black", "Black"),
                                                    ("xr-lemon", "Lemon"),
                                                    ("xr-light-blue", "Light blue"),
                                                    ("xr-pink", "Pink"),
                                                    ("xr-purple", "Purple"),
                                                    ("xr-light-green", "Light green"),
                                                    ("xr-warm-yellow", "Warm yellow"),
                                                    ("xr-bright-pink", "Bright pink"),
                                                    ("xr-red", "Red"),
                                                    ("xr-dark-blue", "Dark blue"),
                                                    ("xr-angry", "Angry"),
                                                    ("xr-white", "White"),
                                                    ("xr-light-grey", "Light grey"),
                                                    ("xr-grey", "Grey"),
                                                    ("xr-dark-grey", "Dark grey"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            help_text='Link to an internal page. Is overwritten by "external link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.core.blocks.URLBlock(
                                                            help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "form",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "form_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                [
                                                    "xr_newsletter.EmailFormPage",
                                                    "xr_newsletter.NewsletterFormPage",
                                                ]
                                            ),
                                        ),
                                        (
                                            "font_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "Green"),
                                                    ("xr-black", "Black"),
                                                    ("xr-lemon", "Lemon"),
                                                    ("xr-light-blue", "Light blue"),
                                                    ("xr-pink", "Pink"),
                                                    ("xr-purple", "Purple"),
                                                    ("xr-light-green", "Light green"),
                                                    ("xr-warm-yellow", "Warm yellow"),
                                                    ("xr-bright-pink", "Bright pink"),
                                                    ("xr-red", "Red"),
                                                    ("xr-dark-blue", "Dark blue"),
                                                    ("xr-angry", "Angry"),
                                                    ("xr-white", "White"),
                                                    ("xr-light-grey", "Light grey"),
                                                    ("xr-grey", "Grey"),
                                                    ("xr-dark-grey", "Dark grey"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    (
                                                        "xr-transparent",
                                                        "None / Transparent",
                                                    ),
                                                    ("xr-green", "Green"),
                                                    ("xr-black", "Black"),
                                                    ("xr-lemon", "Lemon"),
                                                    ("xr-light-blue", "Light blue"),
                                                    ("xr-pink", "Pink"),
                                                    ("xr-purple", "Purple"),
                                                    ("xr-light-green", "Light green"),
                                                    ("xr-warm-yellow", "Warm yellow"),
                                                    ("xr-bright-pink", "Bright pink"),
                                                    ("xr-red", "Red"),
                                                    ("xr-dark-blue", "Dark blue"),
                                                    ("xr-angry", "Angry"),
                                                    ("xr-white", "White"),
                                                    ("xr-light-grey", "Light grey"),
                                                    ("xr-grey", "Grey"),
                                                    ("xr-dark-grey", "Dark grey"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption.",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "grid",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "items",
                                            wagtail.core.blocks.StreamBlock(
                                                [
                                                    (
                                                        "teaser",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "heading",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="An optional heading, which is displayed above the block's content.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "page",
                                                                    wagtail.core.blocks.PageChooserBlock(),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="An optional caption, which is displayed below the block's content. Overwrites the page title of the linked page.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.core.blocks.TextBlock(
                                                                        help_text="An optional description, which is displayed below the block's caption. Overwrites the page description of the linked page.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "image",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "heading",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="An optional heading, which is displayed above the block's content.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(),
                                                                ),
                                                                (
                                                                    "alternative_title",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="An optional alternative title, which is displayed on hover. If not given, the image's title attribute will be used instead.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "background_color",
                                                                    wagtail.core.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "xr-transparent",
                                                                                "None / Transparent",
                                                                            ),
                                                                            (
                                                                                "xr-green",
                                                                                "Green",
                                                                            ),
                                                                            (
                                                                                "xr-black",
                                                                                "Black",
                                                                            ),
                                                                            (
                                                                                "xr-lemon",
                                                                                "Lemon",
                                                                            ),
                                                                            (
                                                                                "xr-light-blue",
                                                                                "Light blue",
                                                                            ),
                                                                            (
                                                                                "xr-pink",
                                                                                "Pink",
                                                                            ),
                                                                            (
                                                                                "xr-purple",
                                                                                "Purple",
                                                                            ),
                                                                            (
                                                                                "xr-light-green",
                                                                                "Light green",
                                                                            ),
                                                                            (
                                                                                "xr-warm-yellow",
                                                                                "Warm yellow",
                                                                            ),
                                                                            (
                                                                                "xr-bright-pink",
                                                                                "Bright pink",
                                                                            ),
                                                                            (
                                                                                "xr-red",
                                                                                "Red",
                                                                            ),
                                                                            (
                                                                                "xr-dark-blue",
                                                                                "Dark blue",
                                                                            ),
                                                                            (
                                                                                "xr-angry",
                                                                                "Angry",
                                                                            ),
                                                                            (
                                                                                "xr-white",
                                                                                "White",
                                                                            ),
                                                                            (
                                                                                "xr-light-grey",
                                                                                "Light grey",
                                                                            ),
                                                                            (
                                                                                "xr-grey",
                                                                                "Grey",
                                                                            ),
                                                                            (
                                                                                "xr-dark-grey",
                                                                                "Dark grey",
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                                (
                                                                    "attribution",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="An optional copyright or attribution text, which is displayed at the bottom right of the image.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="An optional caption, which is displayed below the block's content.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.core.blocks.TextBlock(
                                                                        help_text="An optional description, which is displayed below the block's caption.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "link",
                                                                    wagtail.core.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "internal_link",
                                                                                wagtail.core.blocks.PageChooserBlock(
                                                                                    help_text='Link to an internal page. Is overwritten by "external link".',
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "external_link",
                                                                                wagtail.core.blocks.URLBlock(
                                                                                    help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "video",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "heading",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="An optional heading, which is displayed above the block's content.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "video",
                                                                    wagtail.embeds.blocks.EmbedBlock(),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="An optional caption, which is displayed below the block's content.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.core.blocks.TextBlock(
                                                                        help_text="An optional description, which is displayed below the block's caption.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "slogan",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "heading",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="An optional heading, which is displayed above the block's content.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "text",
                                                                    wagtail.core.blocks.TextBlock(
                                                                        help_text="The text is displayed centered and linebreaks will be preserved.",
                                                                        required=False,
                                                                        rows=1,
                                                                    ),
                                                                ),
                                                                (
                                                                    "font_size",
                                                                    wagtail.core.blocks.IntegerBlock(
                                                                        default=40,
                                                                        help_text="Adjust the font size to fit your needs. Use the preview feature to see how big the font will be rendered.",
                                                                    ),
                                                                ),
                                                                (
                                                                    "font_color",
                                                                    wagtail.core.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "xr-green",
                                                                                "Green",
                                                                            ),
                                                                            (
                                                                                "xr-black",
                                                                                "Black",
                                                                            ),
                                                                            (
                                                                                "xr-lemon",
                                                                                "Lemon",
                                                                            ),
                                                                            (
                                                                                "xr-light-blue",
                                                                                "Light blue",
                                                                            ),
                                                                            (
                                                                                "xr-pink",
                                                                                "Pink",
                                                                            ),
                                                                            (
                                                                                "xr-purple",
                                                                                "Purple",
                                                                            ),
                                                                            (
                                                                                "xr-light-green",
                                                                                "Light green",
                                                                            ),
                                                                            (
                                                                                "xr-warm-yellow",
                                                                                "Warm yellow",
                                                                            ),
                                                                            (
                                                                                "xr-bright-pink",
                                                                                "Bright pink",
                                                                            ),
                                                                            (
                                                                                "xr-red",
                                                                                "Red",
                                                                            ),
                                                                            (
                                                                                "xr-dark-blue",
                                                                                "Dark blue",
                                                                            ),
                                                                            (
                                                                                "xr-angry",
                                                                                "Angry",
                                                                            ),
                                                                            (
                                                                                "xr-white",
                                                                                "White",
                                                                            ),
                                                                            (
                                                                                "xr-light-grey",
                                                                                "Light grey",
                                                                            ),
                                                                            (
                                                                                "xr-grey",
                                                                                "Grey",
                                                                            ),
                                                                            (
                                                                                "xr-dark-grey",
                                                                                "Dark grey",
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                                (
                                                                    "background_color",
                                                                    wagtail.core.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "xr-transparent",
                                                                                "None / Transparent",
                                                                            ),
                                                                            (
                                                                                "xr-green",
                                                                                "Green",
                                                                            ),
                                                                            (
                                                                                "xr-black",
                                                                                "Black",
                                                                            ),
                                                                            (
                                                                                "xr-lemon",
                                                                                "Lemon",
                                                                            ),
                                                                            (
                                                                                "xr-light-blue",
                                                                                "Light blue",
                                                                            ),
                                                                            (
                                                                                "xr-pink",
                                                                                "Pink",
                                                                            ),
                                                                            (
                                                                                "xr-purple",
                                                                                "Purple",
                                                                            ),
                                                                            (
                                                                                "xr-light-green",
                                                                                "Light green",
                                                                            ),
                                                                            (
                                                                                "xr-warm-yellow",
                                                                                "Warm yellow",
                                                                            ),
                                                                            (
                                                                                "xr-bright-pink",
                                                                                "Bright pink",
                                                                            ),
                                                                            (
                                                                                "xr-red",
                                                                                "Red",
                                                                            ),
                                                                            (
                                                                                "xr-dark-blue",
                                                                                "Dark blue",
                                                                            ),
                                                                            (
                                                                                "xr-angry",
                                                                                "Angry",
                                                                            ),
                                                                            (
                                                                                "xr-white",
                                                                                "White",
                                                                            ),
                                                                            (
                                                                                "xr-light-grey",
                                                                                "Light grey",
                                                                            ),
                                                                            (
                                                                                "xr-grey",
                                                                                "Grey",
                                                                            ),
                                                                            (
                                                                                "xr-dark-grey",
                                                                                "Dark grey",
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                                (
                                                                    "background_image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="An optional caption, which is displayed below the block's content.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.core.blocks.TextBlock(
                                                                        help_text="An optional description, which is displayed below the block's caption.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "link",
                                                                    wagtail.core.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "internal_link",
                                                                                wagtail.core.blocks.PageChooserBlock(
                                                                                    help_text='Link to an internal page. Is overwritten by "external link".',
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "external_link",
                                                                                wagtail.core.blocks.URLBlock(
                                                                                    help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "columns",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[(2, "2"), (3, "3"), (4, "4")]
                                            ),
                                        ),
                                        (
                                            "font_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "Green"),
                                                    ("xr-black", "Black"),
                                                    ("xr-lemon", "Lemon"),
                                                    ("xr-light-blue", "Light blue"),
                                                    ("xr-pink", "Pink"),
                                                    ("xr-purple", "Purple"),
                                                    ("xr-light-green", "Light green"),
                                                    ("xr-warm-yellow", "Warm yellow"),
                                                    ("xr-bright-pink", "Bright pink"),
                                                    ("xr-red", "Red"),
                                                    ("xr-dark-blue", "Dark blue"),
                                                    ("xr-angry", "Angry"),
                                                    ("xr-white", "White"),
                                                    ("xr-light-grey", "Light grey"),
                                                    ("xr-grey", "Grey"),
                                                    ("xr-dark-grey", "Dark grey"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    (
                                                        "xr-transparent",
                                                        "None / Transparent",
                                                    ),
                                                    ("xr-green", "Green"),
                                                    ("xr-black", "Black"),
                                                    ("xr-lemon", "Lemon"),
                                                    ("xr-light-blue", "Light blue"),
                                                    ("xr-pink", "Pink"),
                                                    ("xr-purple", "Purple"),
                                                    ("xr-light-green", "Light green"),
                                                    ("xr-warm-yellow", "Warm yellow"),
                                                    ("xr-bright-pink", "Bright pink"),
                                                    ("xr-red", "Red"),
                                                    ("xr-dark-blue", "Dark blue"),
                                                    ("xr-angry", "Angry"),
                                                    ("xr-white", "White"),
                                                    ("xr-light-grey", "Light grey"),
                                                    ("xr-grey", "Grey"),
                                                    ("xr-dark-grey", "Dark grey"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="xr_pages.LocalGroup",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ein Bild, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thank You Page",
                "verbose_name_plural": "Thank You Pages",
            },
            bases=("wagtailcore.page",),
        )
    ]
