# Generated by Django 2.2.2 on 2019-07-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("xr_newsletter", "0012_thankyoupage")]

    operations = [
        migrations.RemoveField(model_name="emailformpage", name="thank_you_text"),
        migrations.RemoveField(model_name="newsletterformpage", name="thank_you_text"),
    ]
