# Generated by Django 2.1.7 on 2019-05-03 10:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("xr_pages", "0036_data_remove_regional_group_page"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtailimages", "0001_squashed_0021"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogEntryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Post date")),
                ("author", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ein Beschreibung, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                        max_length=254,
                    ),
                ),
                (
                    "content",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "text",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    "h3",
                                                    "h4",
                                                    "bold",
                                                    "italic",
                                                    "ul",
                                                    "ol",
                                                    "hr",
                                                    "link",
                                                    "document-link",
                                                ],
                                                help_text="Simple richtext with basic formatting. Use links in order to connect related pages frequently. Ordered lists are rendered with big numbers.For images and videos use the image and video blocks.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alternative_title",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional alternative title, which is displayed on hover. If not given, the image's title attribute will be used instead.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "attribution",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional copyright or attribution text, which is displayed at the bottom right of the image.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            help_text='Link to an internal page. Is overwritten by "external link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.core.blocks.URLBlock(
                                                            help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "video",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        ("video", wagtail.embeds.blocks.EmbedBlock()),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "slogan",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="The text is displayed centered and linebreaks will be preserved.",
                                                required=False,
                                                rows=1,
                                            ),
                                        ),
                                        (
                                            "font_size",
                                            wagtail.core.blocks.IntegerBlock(
                                                default=40,
                                                help_text="Adjust the font size to fit your needs. Use the preview feature to see how big the font will be rendered.",
                                            ),
                                        ),
                                        (
                                            "font_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            help_text='Link to an internal page. Is overwritten by "external link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.core.blocks.URLBlock(
                                                            help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "form",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "form_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                [
                                                    "xr_newsletter.EmailFormPage",
                                                    "xr_newsletter.NewsletterFormPage",
                                                ]
                                            ),
                                        ),
                                        (
                                            "font_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        help_text="Der Inhalt ist nur auf der Detail-Ansicht sichtbar.",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="xr_pages.LocalGroup",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ein Bild, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Entry Page",
                "verbose_name_plural": "Blog Entry Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "content",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "text",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    "h3",
                                                    "h4",
                                                    "bold",
                                                    "italic",
                                                    "ul",
                                                    "ol",
                                                    "hr",
                                                    "link",
                                                    "document-link",
                                                ],
                                                help_text="Simple richtext with basic formatting. Use links in order to connect related pages frequently. Ordered lists are rendered with big numbers.For images and videos use the image and video blocks.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alternative_title",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional alternative title, which is displayed on hover. If not given, the image's title attribute will be used instead.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "attribution",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional copyright or attribution text, which is displayed at the bottom right of the image.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            help_text='Link to an internal page. Is overwritten by "external link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.core.blocks.URLBlock(
                                                            help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "video",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        ("video", wagtail.embeds.blocks.EmbedBlock()),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "slogan",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="The text is displayed centered and linebreaks will be preserved.",
                                                required=False,
                                                rows=1,
                                            ),
                                        ),
                                        (
                                            "font_size",
                                            wagtail.core.blocks.IntegerBlock(
                                                default=40,
                                                help_text="Adjust the font size to fit your needs. Use the preview feature to see how big the font will be rendered.",
                                            ),
                                        ),
                                        (
                                            "font_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.core.blocks.StructBlock(
                                                [
                                                    (
                                                        "internal_link",
                                                        wagtail.core.blocks.PageChooserBlock(
                                                            help_text='Link to an internal page. Is overwritten by "external link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.core.blocks.URLBlock(
                                                            help_text='Link to an external page (https://...). Overwrites "internal link".',
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "align",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("center", "Center"),
                                                    ("full_content", "Full content"),
                                                    ("left", "Left"),
                                                    ("right", "Right"),
                                                    ("full_page", "Full page"),
                                                ],
                                                help_text="Choose the alignment of the block.",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "form",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional heading, which is displayed above the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "form_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                [
                                                    "xr_newsletter.EmailFormPage",
                                                    "xr_newsletter.NewsletterFormPage",
                                                ]
                                            ),
                                        ),
                                        (
                                            "font_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xr-green", "XR green"),
                                                    ("xr-yellow", "XR yellow"),
                                                    ("xr-light-blue", "XR light blue"),
                                                    ("xr-dark-blue", "XR dark blue"),
                                                    ("xr-white", "XR white"),
                                                    ("xr-black", "XR black"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="An optional caption, which is displayed below the block's content.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="An optional description, which is displayed below the block's caption",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        help_text="Der Inhalt ist nur auf der Detail-Ansicht sichtbar.",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="xr_pages.LocalGroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog List Page",
                "verbose_name_plural": "Blog List Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
