# Generated by Django 2.1.7 on 2019-05-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("xr_blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloglistpage",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ein Beschreibung, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="bloglistpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Ein Bild, nicht nur für die Detail-Ansicht, sondern auch für Social Media, Teaser und Listen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
