# Generated by Django 2.2.2 on 2019-06-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("xr_blog", "0004_data_add_missing_colors")]

    operations = [
        migrations.AlterField(
            model_name="blogentrypage",
            name="group",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blog_entries",
                to="xr_pages.LocalGroup",
            ),
        )
    ]
